# -*- coding: utf-8 -*-
"""Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pL4E0o5ZYubt__ht2fRxsWE_Za0XfaWB
"""

pip install pycaret