# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wow_SVH2J8cgQ3FdhE6ZcUd4BIbuaM9K
"""

pip install streamlit